#设置数据源
spring:
  datasource:
    #  配置数据源
    type: com.zaxxer.hikari.HikariDataSource
    #  配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    username: root
    password: root
#设置mybatis相关参数
mybatis-plus:
  configuration:
#    显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    设置全局配置
  global-config:
    db-config:
#      设置全局表的前缀
      table-prefix: t_
      #设置主键生成策略
      id-type: auto
  type-aliases-package: com.ldp.mybatisplusstudy.pojo
  type-enums-package: com.ldp.mybatisplusstudy.enums
